SEARCHING_PROCESSING:bool = False

URL_LINEEDIT_CONTENT:str = ""
SINGLE_INPUT_KEYWORD:str = ""
SINGLE_OUTPUT_PATH_LINEEDIT_CONTENT:str = ""

BATCH_INPUT_SEARCHING_TARGET_LIST_PATH_LINEEDIT_CONTENT:str = ""
BATCH_INPUT_KEYWORD_LIST_PATH_LINEEDIT_CONTENT:str = ""
BATCH_OUTPUT_PATH_LINEEDIT_CONTENT:str = ""




